name = "IdealGasLib"
uuid = "8ea2701e-a7f2-4ad3-bde6-f1a1a263bda4"
authors = ["C. Naaktgeboren <NaaktgeborenC.PhD@gmail.com>"]
version = "0.2.0"

[deps]
EngThermBase = "dffbff30-506a-45ba-b474-e78cc8ad254e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "^1.6"
EngThermBase = "^0.4.2"
Reexport = "^1"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "InteractiveUtils"]
